version: '3.8'
services:
  postgresql_database: 
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    volumes:
      - ./docker/postgres:/var/lib/postgres
    ports:
      - 5432:5432
    networks:
      app_net:
        ipv4_address: 10.0.0.2
  pgadmin: 
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=root@root.org
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    volumes: 
      - ./docker/pgadmin:/var/lib/pgadmin
    networks:
      app_net:
        ipv4_address: 10.0.0.3
  php:
    container_name: php
    build: 
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./symfony:/var/www/backend
    depends_on:
      - postgresql_database
    networks:
      app_net:
        ipv4_address: 10.0.0.5
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./symfony:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgresql_database
    networks:
        app_net:
          ipv4_address: 10.0.0.10
  angular:
    container_name: front
    build: 
      context: .
      dockerfile: ./docker/angular/Dockerfile-an
    volumes:
      - ./front/TestDev:/usr/local/angular
    ports:
      - 4200:4200
    networks:
        app_net:
          ipv4_address: 10.0.0.11
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: 10.0.0.1